### ISSUE TITLE
Felicia's Plate effect working as a Heavy Blade and not a Breath skill.

### ISSUE THREAD

**Issue by ThreshWillRise** [Andu2/FEH-Mass-Simulator#113]
Title. Felicia's Plate procs +1 charge when attacking and when attacked, yet the simulator makes it so that she only gains +1 when attacking herself. Is it possible to just paste the Breath effect code unto the actual HB effect ?

Thank you for all your work btw

**Comment by jyc8** [comment]
Thanks, it should be working correctly now.

**Comment by ThreshWillRise** [comment]
Thank you !
