### ISSUE TITLE
Light Brand is not working properly.

### ISSUE THREAD

**Issue by krbysh** [Andu2/FEH-Mass-Simulator#126]
It compares foe's Def to foe's Res. But not so on.
https://github.com/Andu2/FEH-Mass-Simulator/blob/master/code.js#L6727

And it seems to affect damage for AOE.
Refer to the following tweet (e.g., Leif activates Rising Light in Japanese client).
https://twitter.com/BugsterVirus/status/984051442141970432

**Comment by jyc8** [comment]
Oh it compares foe's def, I'll fix that. I'll also add a check for aoe!
