### ISSUE TITLE
Warrior Princess has effectiveness against all types

### ISSUE THREAD

**Issue by Deltran** [Andu2/FEH-Mass-Simulator#128]
New Hinoka's weapon, Warrior Princess, has weapon effectiveness against all unit types instead of just flying and armor.

**Comment by bardackx** [comment]
@cyfung sent a pull request with the fix, they should be merging it soon

**Comment by jyc8** [comment]
Thanks, merged!

**Comment by Deltran** [comment]
Thanks for the fix!  Looks great to me.
