### ISSUE TITLE
Restore UI to toggle auto-calculations

### ISSUE THREAD

**Issue by Deltran** [Andu2/FEH-Mass-Simulator#129]
In order to directly compare the Changed Victors list between two different builds, it would be better to allow the auto-calculation to be turned off while the build is being updated.  For most users forcing auto-calculate to on makes sense, but there are times when this isn't desirable.

**Comment by bardackx** [comment]
If the lag during building is bothering you set the result filters to something imposible at the moment, like grey meele infantry, is not a fix but a temporary workaround

![image](https://user-images.githubusercontent.com/234251/39259869-3872e3d0-487d-11e8-93b0-ed0febab10e0.png)

**Comment by Deltran** [comment]
Works for me.  thx!

**Comment by jyc8** [comment]
I believe Auto-Calculate can be turned off in Settings under Simulator, let me know if this is what you are looking for.

**Comment by Deltran** [comment]
Yes, it is -- sorry for being dumb, and thanks for pointing out how to do it!
