### ISSUE TITLE
Can you guys add chill def 3 for a B slot?

### ISSUE THREAD

**Issue by q-omar** [Andu2/FEH-Mass-Simulator#131]
The arctic fox version has it but it doesn't have extra lists like his version to test on more enemies.

**Comment by jyc8** [comment]
The Chill skills are hidden by "Show only duel skills" setting, I'll change it so these skills are considered "duel" skills since they do work when the Chill Debuff status is checked.

**Comment by q-omar** [comment]
Ah I see I got it thanks!

**Comment by jyc8** [comment]
Thanks!
