### ISSUE TITLE
Desperation bug

### ISSUE THREAD

**Issue by Archark** [Andu2/FEH-Mass-Simulator#140]
Can't seem to get the simulation to activate desperation in majority of calculations against almost all heroes. Only fighting against certain heroes it seems to proc.

Whether I put 1 health or 75% of max hp, it doesn't seem to activate at all.

**Comment by jyc8** [comment]
I can't seem to reproduce the issue, can you provide an example? Are you sure the hero with desperation can do a follow-up attack (ie. 5+ speed or breaker skill)?

**Comment by Archark** [comment]
Hello, 

I'm trying to recreate it again. It's strange, the problem only seems to occur on devices I use in my workplace. I apologize for the false alarm, probably something to do with my end only. 

Thank you for reaching out though.

**Comment by jyc8** [comment]
No worries, let me know if the issue occurs again.
