### ISSUE TITLE
dark mystletainn's -2 cooldown doesn't seem to be taking effect

### ISSUE THREAD

**Issue by tyleto** [Andu2/FEH-Mass-Simulator#143]
title

**Comment by jyc8** [comment]
It seems to work for me in this [match-up against Cordelia with -40 atk buff](https://imgur.com/a/VyJjooF).

I may have coded the mechanic wrong though, the description say he gains 2 charges "after combat" so I made it only happen after a round is complete (and won't show if he is dead). It'd be great if you can give me an example match-up.

**Comment by jyc8** [comment]
I'm closing this issue at the moment, please let me know/open the issue again if Dark Mystletainn is indeed not working correctly.
