### ISSUE TITLE
 Abel is displayed as "New Hero" in search bar UI

### ISSUE THREAD

**Issue by krbysh** [Andu2/FEH-Mass-Simulator#146]
Abel, top of heroes list, is displayed as "New Hero" in search bar UI.
The others are displayed as respective name.

Probably fix it by changing from "<= 0" to "< 0" in the following conditions.
https://github.com/Andu2/FEH-Mass-Simulator/blob/master/code.js#L2365

Thank you as always!

**Comment by jyc8** [comment]
Good catch, thanks for the quick solution!
