### ISSUE TITLE
Julius Loptous Tome Effect Error

### ISSUE THREAD

**Issue by Nitrohime** [Andu2/FEH-Mass-Simulator#147]
https://media.discordapp.net/attachments/146086547207356416/446167151242641408/unknown.png?width=820&height=702
In the queue it displays that the tome inflicts a -6 penalty in regards to damage, however continuing in the sequence shows it incorrectly reads that Kaze is dealing 14 damage
( 42 - 28[16+6+6=28] = 14)
when he should be dealing 8.
( 36 [42-6=36] - 28[16+6+6=28] = 8) 
https://media.discordapp.net/attachments/146086547207356416/446170077516005377/unknown.png?width=837&height=703
The "effective against" bonus against him however seems to be working as intended as Julia correctly deals 9 damage to Julius.
( 59 [49*.8=39.2*1.5=58.8] - 50 [38+6+6=50] = 9)

**Comment by jyc8** [comment]
Thanks, it should work properly now.

A note for myself and other contributors, Loptous' effect seems to be a new "combat spur" that goes into negative values. Should open the limit for manual spurs and allow negative values as well as check if it stacks with similar debuffs in the future.
