### ISSUE TITLE
Cancel Affinity is not considered in the calculator

### ISSUE THREAD

**Issue by Qumatah** [Andu2/FEH-Mass-Simulator#151]
Hi, when I try a dragonslayer roy build, using cancel affinity, the calculator does not seem to take it into consideration.

**Comment by jyc8** [comment]
Can you give me a specific example? Cancel Affinity only works against gem weapons, -raven tomes, and Triangle Adept as far as I know.

**Comment by Qumatah** [comment]
I tried Roy with cancel affinity vs Nowi and it does not make any difference in the battle simulation

**Comment by jyc8** [comment]
Cancel Affinity only works against Ruby Sword, Sapphire Lance, Emerald Axe, and Triangle Adept.

This means Cancel Affinity will not do anything unless Nowi is using Triangle Adept. It will also neutralize Roy's Triangle Adept if he has it equipped.
