### ISSUE TITLE
SS!Tiki's Breath

### ISSUE THREAD

**Issue by 0blivionknight** [Andu2/FEH-Mass-Simulator#160]
SS!Tiki's breath is not properly adding a special charge when she gets attacked.

**Comment by jyc8** [comment]
Thanks! I forgot it counts both enemy and player attacks.

**Comment by 0blivionknight** [comment]
Thanks for all your hard work!

    On Wednesday, July 11, 2018, 8:37:46 PM PDT, Jason Chen <notifications@github.com> wrote:  
 
 
Thanks! I forgot it counts both enemy and player attacks.
