### ISSUE TITLE
Skills that negate magic users' buffs (e.g. Mulagir, Divine Naga) are not actually negating them.

### ISSUE THREAD

**Issue by koikya** [Andu2/FEH-Mass-Simulator#33]
I've noticed that Lyn (Brave Heroes) and Deirdre's PRF weapons aren't actually negating buffs when I put them against a magic user. It does say that "buffs are nullified by opponent's skill" in the battle report, but adding/removing buffs in the left column still has an effect on the fight. I assume anyone else (if there is anyone else) that has a skill/weapon with a similar effect also has this problem, but haven't tested them out.

**Comment by jyc8** [comment]
Should work properly now, problem was that the relevant def/res variable used in the damage formula wasn't update after mulagir/beorc's/panic/etc.
