### ISSUE TITLE
Kitty Paddle(+) is still affected by Salinn Sheild, Iote's Shield, or Grani's Shield.

### ISSUE THREAD

**Issue by krbysh** [Andu2/FEH-Mass-Simulator#34]
According to "Notifications from Nintendo" (refer to the following), Kitty Paddle(+) is not affected by anti-effective skills such as Salinn Sheild, Iote's Shield, or Grani's Shield.

> Kitty Paddle and Kitty Paddle+ effects against foes using magic cannot be neutralized by Salinn Sheild, Iote's Shield, or Grani's Shield.

How about the following code?

    //Check weapon effective against
    var effectiveBonus = 1;
    if(enemy.moveType == "armored" && (this.has("Hammer") || this.has("Armorslayer") || this.has("Heavy Spear"))){
      effectiveBonus = (enemy.has("Svalinn Shield")) ? 1 : 1.5;
    }
    else if(enemy.moveType == "flying" && (this.hasExactly("Excalibur") || this.weaponType=="bow")){
    effectiveBonus = (enemy.has("Iote's Shield")) ? 1 : 1.5;
    }
    else if(enemy.moveType == "infantry" && (this.has("Poison Dagger"))){
      effectiveBonus = 1.5;
    }
    else if(enemy.moveType == "cavalry" && (this.has("Raudrwolf") || this.has("Blarwolf") || this.has("Gronnwolf") || this.has("Zanbato") || this.has("Ridersbane"))){
      effectiveBonus = (enemy.has("Grani's Shield")) ? 1 : 1.5;
    }
    else if(enemy.weaponType == "dragon" && (this.hasExactly("Falchion") || this.hasExactly("Naga") || this.hasExactly("Divine Naga"))){
      effectiveBonus = 1.5;
    }
    else if((enemy.weaponType == "redtome" || enemy.weaponType == "bluetome" || enemy.weaponType == "greentome")&& (this.has("Kitty Paddle"))){
      effectiveBonus = 1.5;
    }
    
    if(effectiveBonus > 1 ){
      damageText += this.name + "'s attack is increased by " + (effectiveBonus * 100 - 100) + "% from weapon effectiveness.<br>";
    }

**Comment by jyc8** [comment]
That's a weird interaction haha, but the code looks good, I'll push it through.
