### ISSUE TITLE
DEF/ATK Ploy 3

### ISSUE THREAD

**Issue by BebopRS** [Andu2/FEH-Mass-Simulator#35]
DEF Ploy and ATK Ploy 3 are initiating for defender at 5 or less RES instead of 1 or less RES. These are the conditions for DEF/ATK Ploy 1 not 3.

**Comment by jyc8** [comment]
Atk/Def Ploy 1-3 all works when 'your Res' > 'enemy Res'.

I tested Sheena vs Sheena using +1 Res passive and seal, seems to work properly. Do you have a specific example that isn't working?
