### ISSUE TITLE
Warding Stance not working correctly.

### ISSUE THREAD

**Issue by takumisyn** [Andu2/FEH-Mass-Simulator#43]
Warding Stance: "Grants Res+6 during combat when this unit is attacked."

Despite the text in the simulator saying it granted the resistance in the results (and yes, the enemy is the one initiating combat and is a mage) it doesn't seem to actually grant the resistance. Compare to Distant Def 3 and any other Resistance granting skill.

Image Results with both skills:
Distant Def: [Image](https://i.gyazo.com/86643aa0f333a67a981c495431978136.png)
Warding Stance: [Image](https://i.gyazo.com/53e968b17139080f67438f7e889644e7.png)

**Comment by jyc8** [comment]
Thanks! I found the typo.
