### ISSUE TITLE
Slaying Hammer+ applies a Special Cooldown of -1

### ISSUE THREAD

**Issue by Eoinmc97** [Andu2/FEH-Mass-Simulator#45]
While a terrible name from IS, the refind Slaying Weapons like Slaying Hammer+ does not actually have an effect to increase Special Cooldown. It just has 2 more Mt.

**Comment by jyc8** [comment]
Odd, I thought i fixed this yesterday, have you tried hard refreshing with Shift + F5?

**Comment by Eoinmc97** [comment]
Seems to be resolved, keep up the good work! One of the best simulators around.

**Comment by jyc8** [comment]
Thank you!
