### ISSUE TITLE
Buffs during combat

### ISSUE THREAD

**Issue by Charlie-Zheng** [Andu2/FEH-Mass-Simulator#59]
When an enemy unit is buffed by Hone/Fortify/Spurs, it doesn't show in the battle summary. This is mostly problematic when looking at the Sundere's List, since everyone either has +4/+4 Atk/Spd or +6/+6 Atk/Spd. It would be nice for these numbers to be shown next to the base stats in the battle bar thing.

E.g. Slaying Edge Arden would be HP: 60 Atk: 50(+6) Spd: 16(+6) Def: 45 Res: 16

**Comment by jyc8** [comment]
I'm not sure which is better: 

Slaying Edge Arden - HP: 60 Atk: 50(+6) Spd: 16(+6) Def: 45 Res: 16

or 

Slaying Edge Arden - HP: 60 Atk: 56(+6) Spd: 22(+6) Def: 45 Res: 16

I've left it in the first option, but I can swap to the second easily.
