### ISSUE TITLE
Several bugs related to data: hero_skill mismatches, prereq table data misused, inheritancerule for shield pulse.

### ISSUE THREAD

**Issue by Niipa** [Andu2/FEH-Mass-Simulator#6]
hero_skill data is corrupted and the inheritrule for shield pulse is causing issues.

![image](https://user-images.githubusercontent.com/10985559/28749524-741d53f2-7498-11e7-968c-938a56917605.png)

skill_prereq data is not fully complete, there's some missing entries which (I think) is causing the drop down to not have the correct weapon (Ridersbane+)

![image](https://user-images.githubusercontent.com/10985559/28749554-413c33ee-7499-11e7-8334-e77d997fc501.png)

another example

![brokenprereqdata](https://user-images.githubusercontent.com/10985559/28749563-63216ad8-7499-11e7-80bf-caf739dff84f.PNG)

I have a fix in place to fix the corrupted hero_skill data, which affects heroes from the Alm/Celica banners. Currently working to update prereqs.

Regarding skill_prereqs, I think it would be more maintainable to just let all skills be accessible at the start and removing the max skills only option. At the moment, I'm updating the prereqs tables. Some of the entries are wrong (for example, ~~Cancel Affinity 1 required Ridersbane~~ Ridersbane required Slaying Bow+).

**Comment by Meteorchestra** [comment]
For what it's worth, you could keep the max-skills-only functionality by adding a isMax flag to each skill while still getting rid of the prereqs table.

**Comment by Niipa** [comment]
Yea, that's a good suggestion. If the prereq table is only used for finding the max skill we could just add a column to the skill table indicating max skill and filter based on that. Working on it.

**Comment by jyc8** [comment]
This issues should be fixed in the latest db update, let me know if there are more data mismatches.
