### ISSUE TITLE
Ally Support

### ISSUE THREAD

**Issue by LadyUsana** [Andu2/FEH-Mass-Simulator#63]
When you select ally support it changes the stats. At first I thought it was just a visual thing to tell you it was applying the bonuses, but Ally Support bonuses shouldn't let you ploy better. Or at least that was my understanding. To use an Example. Anna vs Roy. Anna has 28 res and roy has 28 res.  Yet if you enable ally it shows Roy being x-ployed and to my knowledge it shouldn't. 

Not a huge issue, but figured I would mention it since I noticed it and didn't see it listed anywhere as a known issue.

**Comment by jyc8** [comment]
Hey thanks for noticing, I used same logic as summoner support when coding it; I'll fix it when I'm back.
