### ISSUE TITLE
Results Options carry over imperfectly to duplicated Chrome tab

### ISSUE THREAD

**Issue by LiamGow** [Andu2/FEH-Mass-Simulator#65]
If a tab of the simulator is duplicated (right click tab -> duplicate), with options selected in the Result Options section (Color, Range, Type, View, Sort), the option will still be visually be selected, but will not be logically selected (Results use defaults instead of what is visually selected).

I recognize that this is somewhat undefined behavior, so I understand if it's wontfix.

(That said, if chrome duplication is something you're interested in supporting, making the whole config carry over would be pretty great.)

**Comment by jyc8** [comment]
I just started playing with browser cache a few updates ago, I think it's actually easier for me to save those options in browser cache than to fix the UI not updating. I'll look into it.

**Comment by LiamGow** [comment]
That did it - thanks!
