### ISSUE TITLE
Would it be possible to build in a Lvl 1 IV calculator?

### ISSUE THREAD

**Issue by LiamGow** [Andu2/FEH-Mass-Simulator#66]
It'd streamline my workflow considerably if I was able to look up IVs on this site, rather than on a wiki.  Not sure how it'd be easiest to implement - probably not as part of the sim itself, so maybe it's outside the scope of this project?

**Comment by jyc8** [comment]
This will probably be a bit more work. If I do implement this, it'll probably be an input box like 'rarity' and 'merge level' that allows input for levels.

**Comment by jyc8** [comment]
I added a tooltip when hovering over hero portrait that shows base stats.

**Comment by jyc8** [comment]
Should be fully functional with IV and rarity changes now.

**Comment by LiamGow** [comment]
Absolutely perfect!  Thanks so much!
