### ISSUE TITLE
Blade Tomes

### ISSUE THREAD

**Issue by plachance14** [Andu2/FEH-Mass-Simulator#74]
Hi,

I was doing some simulations with Nino, and saw that in the summary popup windows, it showed this:
![bug in duel simulator](https://user-images.githubusercontent.com/25864406/35012601-ebdde20e-facf-11e7-80ac-41e4befba3c8.png)

That is incorrect because it shows Ayra getting bonus attack from the blade tome, based on her buffs, which should not happen, since she does not have the blade tome equipped.  I'm not sure if this is effecting the actual calculations of the simulation, or if it is purely a display bug, but it seems like it would be worth addressing either way.

**Comment by jyc8** [comment]
I think it's a display issue, let me quickly fix it.

**Comment by jyc8** [comment]
Testing if bladetome buffs affect enemy Heavy Blade effects. 

eg. Ike attacks Nino (with buffs), will Ike gain an extra charge?

**Comment by plachance14** [comment]
That is an interesting question.  According to the wiki it effects stuff like bonfire if she has the equipped, so I think it is safe to assume it would also effect whether or not an enemy's heavy blade is triggered, but I'm not sure.  I'm also not sure whether or not the mass simulator handles that properly.

**Comment by jyc8** [comment]
Yeah, bladetome and blizzard wording are a bit different and confusing, I'll be confirming this when I get a chance.

**Comment by jyc8** [comment]
[https://imgur.com/a/1swus](https://imgur.com/a/1swus)

Seems to apply on defense and affects Heavy Blade. 

The combat tooltip will show the bonus on both attack and defense phases because of how effective attack is calculated, it is not added twice though. May fix later.
