### ISSUE TITLE
Distant Atk (Parthia's unique refine) fails to function when being attacked.

### ISSUE THREAD

**Issue by krbysh** [Andu2/FEH-Mass-Simulator#76]
"Distant Atk" effects atk +6 againt "ranged" when not only initiating but also being attacked. maybe...

In MDS, "Distant Atk" effects atk +6 when only initiating such as "Death Blow".
https://github.com/Andu2/FEH-Mass-Simulator/blob/master/code.js#L5015-L5018

**Comment by jyc8** [comment]
Ah for some reason I read it as distant death blow.
