### ISSUE TITLE
Missing 2 atk on Rogue dagger + Res Refine

### ISSUE THREAD

**Issue by Yerguer** [Andu2/FEH-Mass-Simulator#84]
While testing on felicia, i realized 2 atk where missing. 
Checking with my account, Rogue dagger+ with Res refining has 12 mt. 
In the simulator Rogue dagger+ has 7 mt and the Res refining adds 3. it should add 5.

this is the build i was testing on:

Felicia (5★+4 +res -hp Summoner: s Ally: s)  
Weapon: Rogue Dagger+  
Refine: Res Bonus - Rogue Dagger  
Assist: Reposition  
Special: Glacies  
A: Attack Res 2  
B: Guard 3  
C: Atk Ploy 3  
S: Distant Def 3  

Hope this is clear enough, thank you in advance

**Comment by jyc8** [comment]
Hmm, looks like the second dagger refinery with mistaken values, I'll go through all the daggers today.
