### ISSUE TITLE
Swift Winds Balm Missing

### ISSUE THREAD

**Issue by SensaiGallade** [Andu2/FEH-Mass-Simulator#86]
Hiya, 

I noticed while playing around with Priscilla that Swift Winds Balm was missing from the specials. Upon further inspection, all healers except Serra, Clarine and Bride Lyn, who have Swift Winds Balm as their base special, are missing the ability to equipt the special.

![image](https://user-images.githubusercontent.com/36089723/35758465-1dd58c18-086c-11e8-89d9-588431757b11.png)

Thank you.

**Comment by jyc8** [comment]
Ahhh I made a mistake and made Swift-Winds Balm a prereq of Radiant Aether, and it got hidden as a non-max skill. I'll quickly fix this.

**Comment by jyc8** [comment]
Although technically, the balm specials shouldn't show up unless the duel only option is deselected since they don't affect duel outcomes...
