### ISSUE TITLE
4 star Est has no access to Heavy Spear+

### ISSUE THREAD

**Issue by pharnb** [Andu2/FEH-Mass-Simulator#87]
Picking est and dropping her to 4 stars removes the "+" from "Heavy Spear+" but does not let me pick "Heavy Spear+" anymore.  This is very low priority since I'd be choosing "Slaying Spear" anyway.

![](https://i.gyazo.com/a3e6b6cee74826eba635b6b26b84fd91.png)

**Comment by jyc8** [comment]
I looked into a few other heroes at 4 star, seems to affect the ones with upgradable weapons.
