### ISSUE TITLE
No weapon Caeda kills PA Azura

### ISSUE THREAD

**Issue by Emalisha** [Andu2/FEH-Mass-Simulator#96]
It's in the title.

**Comment by Emalisha** [comment]
Ok so I just came back to see this issue has been put as a low priority issue.
Just gonna add that this is a problem for any unit in the simulator.

And even if, the calcs are correct after assigning a weapon to the character, this should not be a thing, and might let people choose a different simulator.

**Comment by jyc8** [comment]
I believe ASFox's version of the simulator has this bug fixed, you can find his simulator here:

[http://arcticsilverfox.com/feh_sim/](http://arcticsilverfox.com/feh_sim/)

This is an open source project, feel free to push a fix and I will merge it after testing.

**Comment by Emalisha** [comment]
His simulator is not as complete as this one imo.

Gonna look at the code, even though I don't think I could find the error if someone else can't see it.

**Comment by jyc8** [comment]
It's Chinese new years this week and I'm rather busy, I'll get to it when I have more free time.

**Comment by Emalisha** [comment]
In the declaration of the calculate function (starts at line 3674), I guess you could just add an if that checks if the challenger starts the battle with or without a weapon. If it's not the case, just let the vars wins, losses and inconclusives at 0 and don't initiate the fightResults vector.

That's how I would do it with the little understanding I have of your code...
