### ISSUE TITLE
Cooldown Count Null

### ISSUE THREAD

**Issue by randomanon17** [Andu2/FEH-Mass-Simulator#99]
I was testing stuff with Hana, giving her Glimmer, Killing edge AND Quickened pulse; there's an issue with this though.
Glimmer has a cooldown of two, and both Killing Edge and Quickened Pulse add a -1 cooldown count. This makes it look inside of the simulator that Glimmer has a countdown of 0 and can be used in every turn, but in the game you always have a minimum of 1 cooldown to trigger the special skill, which I also tested right now.
It'll probably be as easy as to make the CD variable always a minimum of 1

**Comment by jyc8** [comment]
Hmm I got the following result with [Hana + Killing Edge + QP](https://imgur.com/a/bxMBE):
I reduced her attack with a -30 debuff while giving opponents at +50 buff, then added two Challenger turns.

- [Against Arvis.](https://imgur.com/a/QKwqy)
- [Against Caeda.](https://imgur.com/a/Poyib)
- [Against Narcian.](https://imgur.com/a/gs2FV)

It looks okay to me in these instances, do you have a specific example I can test?
